### ISSUE TITLE
确实无法扫码

### ISSUE THREAD

**Issue by l406054531** [Atoppos/zhihuishu#3]
![image](https://user-images.githubusercontent.com/67196408/231176391-62119946-b1b1-4276-be54-c2b92396bec2.png)

**Comment by Atoppos** [comment]
这个是字体原因导致加载图片出错，在首次运行程序时，需要将控制台字体改为MS Gothic，以解决二维码图片的加载的问题。
双击程序运行后，在弹出的控制台上方边框处点击鼠标右键，选择属性，选择字体，更改字体即可
