### ISSUE TITLE
源代码110行静音与1.5倍速度按钮目前，selenium无法查找到，可以注释，否则无法运行

### ISSUE THREAD

**Issue by oldoldcoder** [Atoppos/zhihuishu#5]
# ActionChains(driver).move_to_element(contro).click(driver.find_element(By.XPATH,"//div[@class='volumeIcon']")).perform()
    print('已静音')
    # ActionChains(driver).move_to_element(contro).move_to_element(driver.find_element(By.XPATH,"//div[@class='speedBox']")).click(driver.find_element(By.XPATH,"//div[@class='speedList']/div[1]")).perform()
    print('已开启1.5倍速')
    这两行代码目前前端变更后无法找到对应元素，建议注释或者处理容错，注释后目前可以稳定运行

**Comment by Atoppos** [comment]
非常感谢你的反馈，方便问一下选课类型吗，我目前没有智慧树的课，所以调试修改起来比较困难
